---
dist: xenial
language: ruby
cache:
  - bundler
#  directories:
#    - /home/travis/.rvm/
before_install:
    - gem update --system
    - gem install bundler
#    - sudo apt-get install -y pandoc
addons:
  apt:
    update: true
    packages:
      - pandoc
